# Set theme
remote_theme: daviddarnes/alembic@main

# 1. File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# 2. Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# 3. Gem settings
paginate: 5
paginate_path: blog/page:num

# 4. Jekyll settings
permalink: pretty
# timezone: America/New_York

# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Find notes for each class here!"

# 6. Jekyll collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8
title: '98-389: Introduction to Nail Art'
description: 'A CMU StuCo that brings self-expression right to your fingertips. 💅'
logo: "/assets/logos/nail-tartan-logo.png"
url: 'https://leesue630.github.io/intro-nail-art/'
baseurl: '/'
repo: "https://github.com/leesue630/intro-nail-art"

# 8. Site favicons
favicons:
  180: '/assets/logos/nail-tartan-logo.png'

# 9. Header nav
navigation_header:
- title: "Overview"
  url: /
- title: "Syllabus"
  url: /syllabus/
- title: Showcase
  url: /showcase/
- title: Resources
  url: /resources/
- title: FAQ
  url: /faq/
- title: 🔎
  url: /search/

# Footer nav
navigation_footer:
- title: ✨💅✨
  # url: "#top"
